services:
  nginx:
    image: nginx:alpine
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://127.0.0.1:${NGINX_PORT}/']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      client:
        condition: service_healthy
      server:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - scribble-net

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        - REPO_URL
    volumes:
      - ./client:/app/client
      - ./shared:/app/shared
      - /app/node_modules
    environment:
      - PORT=${CLIENT_PORT}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    healthcheck:
      test:
        ['CMD', 'wget', '--spider', '-q', 'http://127.0.0.1:${CLIENT_PORT}/']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    env_file:
      - .env
    networks:
      - scribble-net

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
      args:
        - REPO_URL
    volumes:
      - ./server:/app/server
      - ./server/docker.tsconfig.json:/app/server/tsconfig.json
      - ./server/tsconfig.json:/app/server/local.tsconfig.json
      - ./shared:/app/shared
      - /app/node_modules
    environment:
      - PORT=${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    healthcheck:
      test:
        ['CMD', 'wget', '--spider', '-q', 'http://127.0.0.1:${SERVER_PORT}/']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    env_file:
      - .env
    networks:
      - scribble-net

networks:
  scribble-net:
    driver: bridge
