services:
  client:
    build:
      target: production
    environment:
      - NODE_ENV=production
      - API_URL=http://server:${SERVER_PORT}
    command: ['nginx', '-g', 'daemon off;']

  server:
    build:
      target: production
    environment:
      - NODE_ENV=production
      - PORT=5001
    command: ['npm', 'start']
