services:
  nginx:
    image: nginx:alpine
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
    depends_on:
      - client
      - server
    env_file:
      - .env
    networks:
      - scribble-net

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        - REPO_URL
    volumes:
      - ./client:/app/client
      - ./shared:/app/shared
      - /app/node_modules
    environment:
      - PORT=${CLIENT_PORT}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    env_file:
      - .env
    networks:
      - scribble-net

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
      args:
        - REPO_URL
    volumes:
      - ./server:/app/server
      - ./server/docker.tsconfig.json:/app/server/tsconfig.json
      - ./server/tsconfig.json:/app/server/local.tsconfig.json
      - ./shared:/app/shared
      - /app/node_modules
    environment:
      - PORT=${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    networks:
      - scribble-net

networks:
  scribble-net:
    driver: bridge
