# fly.toml app configuration file generated for scribble-beasts-client on 2026-01-20T12:51:28-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'scribble-client-jazmo'
primary_region = 'ord'

[env]
  API_URL = "http://scribble-server-jazmo.internal:5001"

[build]
  dockerfile = 'client/Dockerfile'

[build.args]
  VITE_SERVER_URL = "https://scribble-server-jazmo.fly.dev"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
